repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: a007afc45e595996f5d7069d7cb12f5c2a4b56a8
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: black
      - id: isort
      - id: pytest
