repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: a2246a4cbc9100a962c3f196737dc73bf41e162c
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: black
      - id: isort
      - id: pytest
